spring.thymeleaf.mode: HTML
spring.h2.console.enabled : true
spring.datasource.url : jdbc:h2:mem:testdb
spring.h2.console.settings.web-allow-others : false
spring.flyway.locations : classpath:db/migration,classpath:db/testdata
spring.batch.initialize-schema : always
spring.datasource.platform : test